@startuml
'https://plantuml.com/class-diagram

class Client
interface Component{
    int price
}
class Item{
    int price
}
class Bag{
    List<Component> components
    int price
}

Client --right--> Component
Item --up--> Component
Bag --up--> Component
@enduml